### ISSUE TITLE
error running install_script_ubuntu.shd 

### ISSUE THREAD

**Issue by mark-hallman** [google/grr-doc#35] opened 2016-01-21 00:08 UTC
I ran into an error running install_script_ubuntu.sh and I am not sure how to correct it.  Can anyone help? Thanks.

System info:  VMWare 12.1 Windows 10 host  / Ubuntu 14.04 server (VM Guest)  2 GB mem

Received the following error:

Collecting codegen==1.0 (from -r requirements.txt (line 28))
  Downloading codegen-1.0.tar.gz
Collecting distorm3==3.3.0 (from -r requirements.txt (line 29))
  Could not find a version that satisfies the requirement distorm3==3.3.0 (from -r requirements.txt (line 29)) (from versions: 3.3.1)
No matching distribution found for distorm3==3.3.0 (from -r requirements.txt (line 29))
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
#########################################################################################
FAILURE RUNNING: pip install -r requirements.txt
#########################################################################################

**Comment by grrrrrrrrr** [comment] 2016-01-21 10:50
Thanks for the report! This is caused by distorm pulling version 3.3.0.

I updated the install script to point at a requirements.txt with updated version information. Please redownload and this problem should be fixed.

**Closed by grrrrrrrrr** 2016-01-21 10:50 UTC

**Comment by mark-hallman** [comment] 2016-01-21 15:59
Andreas,

  

Thanks so much for the prompt response.

  

**Mark Hallman CHFI CCE EnCE GCFE ****GCFA**

  

mobile: 830-255-1551

email:   [mark.hallman@gmail.com](mailto:mark.hallman@gmail.com)

[![](https://ci6.googleusercontent.com/proxy/mp42xtZc-vTi1pj2JO3w2KCWYwW_th3HC
vWE2_jrAK_M1Bge9zXLMOlLSCHvJzaufEi8iaAZmrOFcE62xcAMTr3Qh6GWhnL0FTMNaI9W1lx6dmm
t-3mvZPgcKdQxt8gXZ4b5Z5FkhsjlqPoGh-D1xzgGDf-
nVb_wZRcb4h99EangsSI=s0-d-e1-ft#https://acclaim-production-
app.s3.amazonaws.com/images/c9cc7432-bfbf-4c3c-889e-176e70323032/Template_GCFE
.png)](https://www.youracclaim.com/badges/e9cf1fa5-5657-4d66-ab43-05663519317d
/public_url)  [![](https://ci6.googleusercontent.com/proxy/KqZPFeRe3FjFPu0_OwE
KqR4xSTMEPm4w0CuDUUFzI66adBPGfq0K_WTPRyoFKYOCvIxjygxKiWcX8tGGylaIkK1qvnmSf4icN
3zl_yz9_cX9IdJ2lEktrHSNo-
UsOGH3r3EMfS0VNDjdi_9bmWoJIqt6VuIC_9GT5u5JHId97JMw1mM=s0-d-e1-ft#https
://acclaim-production-app.s3.amazonaws.com/images/7148df07-dff6-44c7-a39e-
1db1e295a138/Template_GCFA.png) ](https://www.youracclaim.com/badges/7d32446e-
3e8e-4861-b0c9-8db3e72469d3/public_url)  

  

  

  

  

> On Jan 21 2016, at 4:50 am, Andreas Moser &lt;notifications@github.com&gt;
wrote:  

>

> Thanks for the report! This is caused by distorm pulling version 3.3.0.

>

> I updated the install script to point at a requirements.txt with updated
version information. Please redownload and this problem should be fixed.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/google
/grr-doc/issues/35#issuecomment-173535814).![](https://github.com/notification
s/beacon/AQB5gLxPpmKPgIp_YGQXWsOLTuGqmtcDks5pcK9fgaJpZM4HJGad.gif)

**Comment by mark-hallman** [comment] 2016-01-21 16:29
there is a warning being thrown for distorm3.  See below.

  Downloading distorm3-3.3.1.zip (146kB)
    100% |████████████████████████████████| 147kB 1.2MB/s 
  Requested distorm3==3.3.1 from https://pypi.python.org/packages/source/d/distorm3/distorm3-3.3.1.zip#md5=0732bcaa53591ff1c264b2d15c282586 (from -r requirements.txt (line 29)), but installing version None
