### ISSUE TITLE
error running install_script_ubuntu.shd 

### ISSUE THREAD

**Issue by mark-hallman** [google/grr-doc#34] opened 2016-01-21 00:03 UTC
I ran into an error running install_script_ubuntu.sh and I am not sure how to correct it.  Can anyone help.  Thanks.

System info:  VMWare 12.1 Windows 10 host  / Ubuntu 14.04 server (VM Guest)  2 GB mem

Received the following error:

Collecting codegen==1.0 (from -r requirements.txt (line 28))
  Downloading codegen-1.0.tar.gz
Collecting distorm3==3.3.0 (from -r requirements.txt (line 29))
  Could not find a version that satisfies the requirement distorm3==3.3.0 (from -r requirements.txt (line 29)) (from versions: 3.3.1)
No matching distribution found for distorm3==3.3.0 (from -r requirements.txt (line 29))
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
#########################################################################################
FAILURE RUNNING: pip install -r requirements.txt
#########################################################################################

**Comment by grrrrrrrrr** [comment] 2016-01-21 10:48
duplicate of #35

**Closed by grrrrrrrrr** 2016-01-21 10:48 UTC
Labels: duplicate
